// auth
export const AUTH_MODULE_NAME = 'auth';
export const AUTH_ERROR_EXIST_PHONE_NUMBER = 1;
export const AUTH_ERROR_NOT_FOUND_PHONE_NUMBER = 2;
export const AUTH_ERROR_INVALID_CODE = 3;
export const AUTH_ERROR_COOL_TIME = 4;
export const AUTH_ERROR_VERIFICATION_TIMEOUT = 5;
export const AUTH_ERROR_NOT_FOUND_USER = 6;
export const AUTH_ERROR_INVAILD_VERIFICATION = 7;
export const AUTH_ERROR_INVAILD_REFRESH_TOKEN = 8;
// polling
export const POLLING_MODULE_NAME = 'pollings';
export const POLLING_ERROR_EXIST_POLLING = 1;
export const POLLING_ERROR_EXIST_USERROUND = 2;
export const POLLING_ERROR_NOT_INCLUDES_POLLID = 3;
export const POLLING_ERROR_NOT_FOUND_POLLING = 4;
export const POLLING_ERROR_NOT_FOUND_USERROUND = 5;
export const POLLING_ERROR_COOL_TIME = 6;
export const POLLING_ERROR_MIN_FRIENDS = 7;
export const POLLING_ERROR_EXCEED_REFRESH = 8;
export const POLLING_ERROR_NOT_AUTHORIZED = 9;
export const POLLING_ERROR_ALREADY_DONE = 10;
export const POLLING_ERROR_LACK_COIN_AMOUNT = 11;
export const POLLING_ERROR_EXCEED_SKIP = 12;
export const POLLING_ERROR_EMPTY_BODY = 13;
export const POLLING_ERROR_NOT_OPENED = 14;
export const POLLING_ERROR_NOT_FOUND_POLL = 15;
export const POLLING_ERROR_ROUNDEVENT_LOOKUP = 16;
// profile

export const PROFILES_ERROR_NOT_FOUND = 1;
export const PROFILES_ERROR_OWNER_LESS = 2;

export const SCHOOL_MODULE_NAME = 'schools';
export const SCHOOL_ERROR_NOT_FOUND_MY_SCHOOL = 1;
