// polling
export const POLLING_ERROR_EXIST_POLLING = 1;
export const POLLING_ERROR_EXIST_USERROUND = 2;
export const POLLING_ERROR_NOT_INCLUDES_POLLID = 3;
export const POLLING_ERROR_NOT_FOUND_POLLING = 4;
export const POLLING_ERROR_NOT_FOUND_USERROUND = 5;
export const POLLING_ERROR_COOL_TIME = 6;
export const POLLING_ERROR_MIN_FRIENDS = 7;
export const POLLING_ERROR_EXCEED_REFRESH = 8;
export const POLLING_ERROR_NOT_AUTHORIZED = 9;
export const POLLING_ERROR_ALREADY_DONE = 10;
export const POLLING_ERROR_LACK_COIN_AMOUNT = 11;
export const POLLING_ERROR_WAITING_NEXT_DAY = 12;
export const POLLING_ERROR_WAITING_30_MIN = 13;
export const POLLING_ERROR_EXCEED_SKIP = 14;
export const POLLING_ERROR_EMPTY_BODY = 15;
