// auth
export const AUTH_ERROR_EXIST_USERNAME = 1;
export const AUTH_ERROR_EXIST_PHONE_NUMBER = 2;
export const AUTH_ERROR_INVALID_CODE = 3;
export const AUTH_ERROR_VERIFICATION_TIMEOUT = 4;
export const AUTH_ERROR_INVALID_LOGIN = 5;
export const AUTH_ERROR_NOT_FOUND_USERNAME = 6;
export const AUTH_ERROR_COOL_TIME = 7;
export const AUTH_ERROR_NOT_FOUND_USER = 8;

// polling
export const POLLING_ERROR_EXIST_POLLING = 1;
export const POLLING_ERROR_EXIST_USERROUND = 2;
export const POLLING_ERROR_NOT_INCLUDES_POLLID = 3;
export const POLLING_ERROR_NOT_FOUND_POLLING = 4;
export const POLLING_ERROR_NOT_FOUND_USERROUND = 5;
export const POLLING_ERROR_COOL_TIME = 6;
export const POLLING_ERROR_MIN_FRIENDS = 7;
export const POLLING_ERROR_EXCEED_REFRESH = 8;
export const POLLING_ERROR_NOT_AUTHORIZED = 9;
export const POLLING_ERROR_ALREADY_DONE = 10;
export const POLLING_ERROR_LACK_COIN_AMOUNT = 11;
export const POLLING_ERROR_EXCEED_SKIP = 12;
export const POLLING_ERROR_EMPTY_BODY = 13;
